### PR TITLE
redact-fault-1

### LINKED ISSUE #122: redact fault events
fault events help us handle poison events and resubmit the failing events later. they also contain the uow which contains valuable information that can help diagnose the problem. however, this information may contain PII data, it can be very large and may have circular references.

this improvement will redact identified pii data, trim buffers and handle circular references.

it will leave the uow.record element intact to support resubmit. if the uow.record element has pii data then it should be encrypted at the source.

### PR DESCRIPTION
**Pull request by jgilbert01**
Fixes #122

### CODE REVIEW

File: src/flavors/materialize.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ const onEventType = (rule) => faulty((uow) => filterOnEventType(rule, uow));
 const onContent = (rule) => faulty((uow) => filterOnContent(rule, uow));
 
 const toUpdateRequest = (rule) => faultyAsync((uow) =>
-  Promise.resolve(rule.toUpdateRequest(uow, rule))
+  toResolve(rule.toUpdateRequest, uow, rule)
```
Comment (jgilbert01) [inline src/flavors/materialize.js:35]: non async mappers where executed outside the faulty try/catch

File: src/flavors/materialize.js [hunk 2]
```diff
@@ -31,9 +29,7 @@ export const materialize = (rule) => (s) => s // eslint-disable-line import/pref
...
-const toUpdateRequest = (rule) => faultyAsync((uow) =>
-  Promise.resolve(rule.toUpdateRequest(uow, rule))
-    .then((updateRequest) => ({
-      ...uow,
-      updateRequest,
-    })));
+const toUpdateRequest = (rule) => faultyAsyncStream(async (uow) => ({
+  ...uow,
+  updateRequest: await faultify(rule.toUpdateRequest)(uow, rule),
+}));
```
Comment (jgilbert01) [inline src/flavors/materialize.js:35]: non async mappers where executed outside the faulty try/catch

File: src/flavors/cdc.js [hunk 3]
```diff
@@ -43,13 +43,12 @@ const toQueryRequest = (rule) => (uow) => ({
...
-      }))));
+const toEvent = (rule) => faultyAsyncStream(async (uow) => (!rule.toEvent
+  ? Promise.resolve(uow)
+  : ({
+    ...uow,
+    event: {
+      ...uow.event,
+      ...await faultify(rule.toEvent)(uow, rule),
+    },
+  })));
```
Comment (jgilbert01) [inline src/flavors/cdc.js:54]: non async mappers where executed outside the faulty try/catch

Comment (jgilbert01) [reply src/flavors/cdc.js:54]: faultify executes an synchronous function inside a try catch and normalizes it to an async function

Comment (jgilbert01) [reply src/flavors/cdc.js:54]: faultify executes an synchronous function inside a try catch and normalizes it to an async function
